apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: node-sercrt-if
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-sercrt-if 
  name: node-sercrt-if
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: node-sercrt-if 
